# Generated by Django 3.0 on 2020-11-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmearPositiveTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_15_24', models.IntegerField(verbose_name='15-24')),
                ('age_25_34', models.IntegerField(verbose_name='15-24')),
                ('age_35_44', models.IntegerField(verbose_name='15-24')),
                ('age_45_54', models.IntegerField(verbose_name='15-24')),
                ('age_55_64', models.IntegerField(verbose_name='15-24')),
                ('age_65_above', models.IntegerField(verbose_name='15-24')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
