# Generated by Django 3.0 on 2020-11-03 08:33

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smearpositivetb',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='smearpositivetb',
            name='age_25_34',
            field=models.IntegerField(verbose_name='25-34'),
        ),
        migrations.AlterField(
            model_name='smearpositivetb',
            name='age_35_44',
            field=models.IntegerField(verbose_name='35-44'),
        ),
        migrations.AlterField(
            model_name='smearpositivetb',
            name='age_45_54',
            field=models.IntegerField(verbose_name='45-54'),
        ),
        migrations.AlterField(
            model_name='smearpositivetb',
            name='age_55_64',
            field=models.IntegerField(verbose_name='55-64'),
        ),
        migrations.AlterField(
            model_name='smearpositivetb',
            name='age_65_above',
            field=models.IntegerField(verbose_name='65 and Above'),
        ),
    ]
