# Generated by Django 3.0 on 2020-12-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smearpositivetb',
            name='year',
        ),
    ]
