# Generated by Django 3.0 on 2020-12-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0002_remove_smearpositivetb_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retroyears',
            name='created',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='device_created',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='device_modified',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='hostname_created',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='hostname_modified',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='retroyears',
            name='user_modified',
        ),
        migrations.AlterField(
            model_name='retroyears',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
