# Generated by Django 3.0 on 2020-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0002_auto_20201103_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='smearpositivetb',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=None, max_length=12, verbose_name='GENDER'),
        ),
        migrations.AddField(
            model_name='smearpositivetb',
            name='soc_econ_pos_high',
            field=models.IntegerField(default=0, verbose_name='High'),
        ),
        migrations.AddField(
            model_name='smearpositivetb',
            name='soc_econ_pos_low',
            field=models.IntegerField(default=0, verbose_name='Low'),
        ),
        migrations.AddField(
            model_name='smearpositivetb',
            name='soc_econ_pos_middle',
            field=models.IntegerField(default=0, verbose_name='Middle'),
        ),
    ]
