# Generated by Django 3.0 on 2020-11-03 12:10

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('edc_forms', '0003_auto_20201103_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacteriologicalConfirmedPulmonaryTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_15_24', models.IntegerField(verbose_name='15-24')),
                ('age_25_34', models.IntegerField(verbose_name='25-34')),
                ('age_35_44', models.IntegerField(verbose_name='35-44')),
                ('age_45_54', models.IntegerField(verbose_name='45-54')),
                ('age_55_64', models.IntegerField(verbose_name='55-64')),
                ('age_65_above', models.IntegerField(verbose_name='65 and Above')),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=None, max_length=12, verbose_name='GENDER')),
                ('soc_econ_pos_low', models.IntegerField(default=0, verbose_name='Low')),
                ('soc_econ_pos_middle', models.IntegerField(default=0, verbose_name='Middle')),
                ('soc_econ_pos_high', models.IntegerField(default=0, verbose_name='High')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('-created',),
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
