# Generated by Django 3.0 on 2020-12-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0004_auto_20201222_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='smearpositivetb',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_forms.RetroYears'),
        ),
    ]
