# Generated by Django 3.0 on 2020-11-03 12:30

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('edc_forms', '0004_bacteriologicalconfirmedpulmonarytb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPrevalenceSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=60, verbose_name='Cluster Name')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Longitude')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
