# Generated by Django 3.0 on 2020-11-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0005_clusterprevalencesurvey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smearpositivetb',
            options={'ordering': ('-created',), 'verbose_name': 'Smear Positive Pulmonary TB', 'verbose_name_plural': 'Smear Positive Pulmonary TB'},
        ),
        migrations.RemoveField(
            model_name='smearpositivetb',
            name='sex',
        ),
        migrations.AddField(
            model_name='smearpositivetb',
            name='gender_female',
            field=models.IntegerField(default=0, verbose_name='Female'),
        ),
        migrations.AddField(
            model_name='smearpositivetb',
            name='gender_male',
            field=models.IntegerField(default=0, verbose_name='Male'),
        ),
    ]
