# Generated by Django 3.0 on 2020-12-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0005_smearpositivetb_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smearpositivetb',
            name='year',
            field=models.ForeignKey(default='64f1d792-904d-49f8-81f7-48aa430831cb', null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_forms.RetroYears'),
        ),
    ]
