# Generated by Django 3.0 on 2020-11-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0006_auto_20201113_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacteriologicalconfirmedpulmonarytb',
            name='sex',
        ),
        migrations.AddField(
            model_name='bacteriologicalconfirmedpulmonarytb',
            name='gender_female',
            field=models.IntegerField(default=0, verbose_name='Female'),
        ),
        migrations.AddField(
            model_name='bacteriologicalconfirmedpulmonarytb',
            name='gender_male',
            field=models.IntegerField(default=0, verbose_name='Male'),
        ),
    ]
