# Generated by Django 3.0 on 2021-01-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0008_auto_20201230_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smearpositivetb',
            name='year',
        ),
    ]
