# Generated by Django 3.0 on 2021-01-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0008_auto_20201230_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smearpositivetb',
            old_name='year',
            new_name='year_id',
        ),
    ]
