# Generated by Django 3.0 on 2021-01-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0009_remove_smearpositivetb_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='smearpositivetb',
            name='year',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_forms.RetroYears'),
        ),
    ]
