# Generated by Django 3.0 on 2021-01-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0010_smearpositivetb_year'),
        ('edc_forms', '0011_auto_20210106_0814'),
    ]

    operations = [
    ]
