# Generated by Django 3.0 on 2021-02-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0016_historicalsmearpositivetb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSmearPositiveTB',
        ),
    ]
