# Generated by Django 3.0 on 2021-03-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_forms', '0020_auto_20210329_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsmearpositivetb',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='smearpositivetb',
            name='initials',
        ),
    ]
