# Generated by Django 3.0 on 2021-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcstheme',
            name='theme',
            field=models.BooleanField(default=False, verbose_name='Dark Mode'),
        ),
    ]
