# Generated by Django 3.0 on 2021-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_theme', '0002_auto_20210113_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcstheme',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme')], max_length=8, verbose_name='Dark Mode'),
        ),
    ]
