# Generated by Django 3.0 on 2021-01-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edc_theme', '0006_remove_edcstheme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstheme',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='edcstheme',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme')], max_length=8, verbose_name='EDC Theme'),
        ),
    ]
