# Generated by Django 3.0 on 2021-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_theme', '0007_auto_20210118_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcstheme',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme')], default='light', max_length=8, verbose_name='EDC Theme'),
        ),
    ]
