# Generated by Django 3.0 on 2021-03-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_crfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Require CRF'),
        ),
    ]
