# Generated by Django 3.0 on 2021-03-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_crfs', '0002_auto_20210302_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Study CRF nme'),
        ),
    ]
