# Generated by Django 3.0 on 2021-01-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EdcsTheme',
        ),
    ]
